version: '2'
services:
  # exec format for signal catching
  bot:
    build: .
    command: ["python3", "/usr/src/app/bot.py"]
    restart: always
  spider:
    build: .
    command: ["python3", "/usr/src/app/spider.py"]
    restart: always
  notifier:
    build: .
    command: ["python3", "/usr/src/app/notifier.py"]
    restart: always
  mongo:
    image: "mongo:4.2"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    volumes:
      - ./db:/data/db
    expose:
      - "27017"
    restart: on-failure
